/* No credentials or remote stock APIs in the browser. Data comes from the local adapter or teaching snapshot. */
'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data,presets,active=[],result=[],tab='均線與獲利',mode='table',sortKey='gain3',sortDown=true;
const selected=new Set(),favorites=new Set(JSON.parse(localStorage.getItem('picker-favorites')||'[]'));
const base=[['股票代號','symbol'],['價格','price'],['漲跌幅 %','change'],['成交量 張','volume']];
const tabs={
 '均線與獲利':[['5日均價','ma5'],['10日均價','ma10'],['20日均價','ma20'],['5週均價','wma5'],['10週均價','wma10'],['20週均價','wma20'],['季度ROE %','ROE季'],['季度ROA %','ROA季']],
 '日籌碼':[['家數差','家數差'],['集中度 %','籌碼集中度'],['主力 張','主力買賣超'],['三大法人 張','三大法人'],['外資 張','外資'],['投信 張','投信'],['自營 張','自營'],['自營避險 張','自營避險'],['八大官股 張','八大官股'],['融資增減 張','融資增減'],['融券增減 張','融券增減'],['借券賣出餘額 張','借券賣出餘額'],['當沖量 張','當沖量']],
 '大戶持股':[['400張以上人數','大戶人數'],['400張以上持股比例 %','大戶比例']],
 '營收動能':[['月營收年增 %','月營收年增'],['月營收月增 %','月營收月增'],['3月合計年增 %','revenue3_yoy'],['3日漲幅 %','gain3'],['5日漲幅 %','gain5'],['相對大盤5日 百分點','relative5']],
 '風險指標':[['20日箱形振幅 %','box_range'],['Beta一年','Beta一年'],['負債比率 %','負債比率'],['流動比率 %','流動比率']],
 '價值評估':[['本益比','pe'],['股價淨值比','股價淨值比'],['年度殖利率 %','年度殖利率']],
 '財報':['營業收入','營業毛利','營業費用','營業淨利','營業外收入及支出','稅前純益','所得稅費用','稅後純益','eps','資產','資產_流動','現金','庫存','總應收帳款','資產_非流動','資產_無形','固定資產','負債總額','負債_流動','負債_非流動','股東權益_總額','營運現金流','投資現金流','籌資現金流','資本支出','自由現金流','淨現金流_千'].map(k=>[k+(k==='eps'?' 元':' 千元'),k]),
};
const labels={available:'雪鴞可計算'};
function cards(){let q=$('#search').value.trim().toLowerCase();let items=presets.filter(p=>(p.title+p.description+p.conditions.join('')).toLowerCase().includes(q));
 $('#card-count').textContent=`${items.length} / ${presets.length} 個策略`;
 $('#cards').innerHTML=items.map(p=>`<article class="strategy ${selected.has(p.id)?'selected':''}" data-id="${p.id}"><div class="card-title"><input type="checkbox" aria-label="組合選擇 ${esc(p.title)}" data-select="${p.id}" ${selected.has(p.id)?'checked':''}><button data-run="${p.id}">${esc(p.title)}</button></div><p class="description">${esc(p.description)}</p>${p.conditions.slice(0,3).map(c=>`<div class="condition">${esc(c)}</div>`).join('')}${p.conditions.length>3?`<details><summary>展開更多（${p.conditions.length-3}條）</summary>${p.conditions.slice(3).map(c=>`<div class="condition">${esc(c)}</div>`).join('')}</details>`:''}<span class="badge ${p.status}">${labels[p.status]}</span><details><summary>規則與資料核對</summary><p>${esc(p.note)}</p></details></article>`).join('')||'<p class="empty">沒有符合的策略。查股票請先執行策略，再搜尋股號。</p>';
 $('#selection-count').textContent=`已選 ${selected.size} 個策略`;
}
function pass(r,id){if(id==='gain'){let ranked=[...data.rows].filter(x=>x.gain3!=null).sort((a,b)=>b.gain3-a.gain3);return ranked.slice(0,Math.max(1,Number($('#gain-limit').value)||150)).some(x=>x.symbol===r.symbol)}return r.passes.includes(id)}
function filterRows(){let combo=$('#combine-mode').value,min=Math.max(0,Number($('#min-volume').value)||0),q=$('#result-search').value.trim().toLowerCase();return data.rows.filter(r=>{let checks=active.map(id=>pass(r,id));return(active.length===0||(combo==='and'?checks.every(Boolean):checks.some(Boolean)))&&(min===0||(r.volume!=null&&r.volume>=min))&&(!$('#only-favorite').checked||favorites.has(r.symbol))&&(!q||(r.symbol+r.name).toLowerCase().includes(q))})}
function openResults(ids,fav=false){active=ids;$('#result-search').value='';$('#only-favorite').checked=fav;$('#detail').hidden=true;$('#results-title').textContent=ids.length?ids.map(id=>presets.find(p=>p.id===id).title).join(' ＋ '):'我的收藏';
 $('#alert-panel').hidden=!fav;if(fav)loadAlerts();
 $('#rule-note').textContent=ids.map(id=>{let p=presets.find(x=>x.id===id);return p.title+'：'+p.note}).join('　')||'收藏只存於此瀏覽器，並非持倉資料。';
 refresh();
 if(!$('#results').open)$('#results').showModal();
}
function fmt(v){return v==null?'資料未提供':typeof v==='number'?v.toLocaleString('zh-TW',{maximumFractionDigits:2}):esc(v)}
function refresh(){result=filterRows();$('#result-meta').textContent=`找到 ${result.length} 檔符合條件股票 ｜ ${data.asof} ｜ ${data.mode==='teaching_sample'?'教學小樣本':'本機資料範圍'} ${data.universe_count} 檔 ｜ 候選名單尚待交易計畫`;
 let note=active.map(id=>{let p=presets.find(x=>x.id===id);return p.title+'：'+p.note}).join('　');let keys=tabs[tab].map(x=>x[1]);let periods=[...new Set(keys.map(k=>data.fundamental_periods[k]).filter(Boolean))];$('#rule-note').textContent=(note||'收藏清單。')+(periods.length?'　欄位最新期間：'+periods.join('、'):'')+'　個別公司資料不足顯示缺值；財報期間須另核對公告日。';
 result.sort((a,b)=>{let av=a[sortKey],bv=b[sortKey];if(av==null)return bv==null?0:1;if(bv==null)return-1;return(typeof av==='string'?av.localeCompare(bv):av-bv)*(sortDown?-1:1)});renderTable();renderCharts();}
function renderTable(){let columns=[...base,...tabs[tab]];$('#table-head').innerHTML='<tr>'+columns.map(([title,key])=>`<th><button data-sort="${key}">${esc(title)} ${sortKey===key?(sortDown?'↓':'↑'):''}</button></th>`).join('')+'<th>收藏</th></tr>';
 $('#table-body').innerHTML=result.length?result.map(r=>'<tr>'+columns.map(([,key],i)=>`<td class="${key==='change'?(r.change>=0?'up':'down'):''}">${i===0?`<button class="stock-link" data-detail="${r.symbol}">${esc(r.name)}<small>${r.symbol}</small></button>`:fmt(r[key])}</td>`).join('')+`<td><button data-fav="${r.symbol}" aria-label="收藏 ${r.symbol}" aria-pressed="${favorites.has(r.symbol)}">${favorites.has(r.symbol)?'★':'☆'}</button></td></tr>`).join(''):`<tr><td colspan="${columns.length+1}" class="empty">目前沒有符合的股票。先查資料範圍與單位，再考慮是否調整條件。</td></tr>`;
}
function lineChart(r){let vals=r.chart.map(p=>p.value);if(vals.length<2)return'<p>圖表資料不足</p>';let min=Math.min(...vals),max=Math.max(...vals),range=max-min||1;let points=vals.map((v,i)=>`${(i/(vals.length-1)*600).toFixed(2)},${(155-(v-min)/range*140).toFixed(2)}`).join(' ');return `<svg viewBox="0 0 600 180" role="img" aria-label="${esc(r.name)}收盤走勢，第一日等於100"><path d="M0 155H600" stroke="#34383f"/><polyline points="${points}" fill="none" stroke="#78a7ff" stroke-width="2.5"/><text x="2" y="177" fill="#a1a8b2" font-size="14">${r.chart[0].date}</text><text x="480" y="177" fill="#a1a8b2" font-size="14">${r.chart.at(-1).date}</text></svg>`}
function renderCharts(){$('#charts').innerHTML=result.map(r=>`<article class="chart"><h3>${esc(r.name)} <small>${r.symbol}</small></h3><span>${fmt(r.price)}元　<span class="${r.change>=0?'up':'down'}">${fmt(r.change)}%</span></span>${lineChart(r)}<p>${r.chart_unit}；近${r.chart.length}個交易日。量 ${fmt(r.volume)}張</p><button data-detail="${r.symbol}">詳情 ${r.symbol}</button></article>`).join('')||'<p class="empty">沒有可顯示的圖表。</p>'}
function detail(symbol){let r=data.rows.find(x=>x.symbol===symbol);$('#detail').hidden=false;$('#detail').innerHTML=`<h3>${esc(r.name)} ${r.symbol}｜資料核對</h3>${lineChart(r)}<p>價格 ${fmt(r.price)}元，成交量 ${fmt(r.volume)}張；資料日 ${data.asof}。</p><p>符合：${r.passes.map(id=>presets.find(p=>p.id===id)?.title||id).map(esc).join('、')||'目前無已知條件通過'}</p><p>想進場還缺：觸發時間、成交價、停損／失效條件、出場、部位。請先在下方紀錄自己的假設。</p><button id="detail-close">收起詳情</button>`;$('#detail').scrollIntoView({behavior:'smooth',block:'nearest'})}
/* Price alerts: the local server stores them in .local; the Bot token is write-only and never read back. */
const isLocal=location.hostname==='127.0.0.1'||location.hostname==='localhost';
let alertState={alerts:[],telegram:null};
async function api(path,body){let r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});let j=await r.json().catch(()=>({error:`HTTP ${r.status}`}));if(!r.ok)throw Error(j.error||`HTTP ${r.status}`);return j}
function tgStatus(t){$('#tg-status').textContent=t?.configured?`已設定：通知送到 ${t.target_hint}。Token 存在本機，不再顯示。`:'尚未設定：填 Bot Token 與頻道後按「存到本機」。'}
async function loadAlerts(){let local=isLocal;$('#alert-local-note').hidden=local;document.querySelectorAll('#alert-panel input,#alert-panel select,#alert-panel button').forEach(x=>x.disabled=!local);
 if(local){try{alertState=await api('api/alerts');tgStatus(alertState.telegram);if(alertState.telegram?.target_hint?.startsWith('@'))$('#tg-chat').value=alertState.telegram.target_hint}catch(e){$('#alerts-status').textContent='讀不到本機到價設定：'+e.message}}
 $('#alert-rows').innerHTML='';renderAlertRows()}
function alertDrafts(){let out={};document.querySelectorAll('#alert-rows tr[data-symbol]').forEach(tr=>{let v=k=>tr.querySelector(`[data-k="${k}"]`);out[tr.dataset.symbol]={condition:v('condition').value,price:v('price').value,stop:v('stop').value,note:v('note').value,enabled:v('enabled').checked,reset:tr.dataset.reset==='1'}});return out}
function alertStatus(a){if(!a)return'未設定';if(a.status==='triggered')return`<span class="status-hit">已觸發 ${esc(a.triggered_at?.slice(5,16).replace('T',' '))}｜${fmt(a.triggered_price)}</span> <button data-reset>重新監看</button>`;if(a.status==='check_delivery')return`<span class="status-hit">傳送狀態不明，先看手機</span> <button data-reset>重新監看</button>`;return a.enabled?'監看中':'暫停'}
function renderAlertRows(){let saved=Object.fromEntries(alertState.alerts.map(a=>[a.symbol,a])),drafts=alertDrafts(),ids=[...favorites];
 $('#alert-rows').innerHTML=ids.length?ids.map(s=>{let r=data.rows.find(x=>x.symbol===s),a=drafts[s]||saved[s]||{},state=drafts[s]?.reset?null:saved[s];let val=x=>x==null?'':esc(x);
  return `<tr data-symbol="${esc(s)}" data-name="${esc(r?.name||saved[s]?.name||'')}"${drafts[s]?.reset?' data-reset="1"':''}><td>${esc(r?.name||saved[s]?.name||'')}<small>${esc(s)}</small></td><td>${fmt(r?.price)}</td><td><select data-k="condition" aria-label="${esc(s)} 進場條件"><option value="gte"${a.condition!=='lte'?' selected':''}>突破 ≥</option><option value="lte"${a.condition==='lte'?' selected':''}>回到 ≤</option></select></td><td><input data-k="price" type="number" min="0" step="0.01" value="${val(a.price)}" aria-label="${esc(s)} 進場價" placeholder="必填"></td><td><input data-k="stop" type="number" min="0" step="0.01" value="${val(a.stop)}" aria-label="${esc(s)} 停損價" placeholder="選填"></td><td><input data-k="note" maxlength="200" value="${val(a.note)}" aria-label="${esc(s)} 計畫備註" placeholder="例：突破前高、量大於5日均量"></td><td><input data-k="enabled" type="checkbox" ${a.enabled!==false?'checked':''} aria-label="${esc(s)} 啟用"></td><td>${drafts[s]?.reset?'儲存後重新監看':alertStatus(state)}</td></tr>`}).join(''):'<tr><td colspan="8" class="empty">還沒有收藏。先在選股結果按 ☆，再回來寫進場計畫。</td></tr>';
 if(!isLocal)document.querySelectorAll('#alert-rows input,#alert-rows select,#alert-rows button').forEach(x=>x.disabled=true)}
$('#alert-rows').addEventListener('click',e=>{let b=e.target.closest('[data-reset]');if(!b)return;let tr=b.closest('tr');tr.dataset.reset='1';b.parentElement.textContent='儲存後重新監看'});
$('#alerts-save').onclick=async()=>{let drafts=alertDrafts(),alerts=[];for(let tr of document.querySelectorAll('#alert-rows tr[data-symbol]')){let s=tr.dataset.symbol,d=drafts[s];if(d.price==='')continue;alerts.push({symbol:s,name:tr.dataset.name,condition:d.condition,price:Number(d.price),stop:d.stop===''?null:Number(d.stop),note:d.note,enabled:d.enabled,reset:d.reset})}
 try{let j=await api('api/alerts',{alerts});alertState.alerts=j.alerts;$('#alert-rows').innerHTML='';renderAlertRows();$('#alerts-status').textContent=`已存 ${j.saved} 檔到 .local/price-alerts.json；沒填進場價的不監看。接著執行盯盤程式。`}catch(e){$('#alerts-status').textContent='未儲存：'+e.message}};
$('#tg-save').onclick=async()=>{try{let j=await api('api/telegram',{token:$('#tg-token').value,chat_id:$('#tg-chat').value});$('#tg-token').value='';alertState.telegram=j.telegram;tgStatus(j.telegram)}catch(e){$('#tg-status').textContent='未儲存：'+e.message}};
$('#tg-test').onclick=async()=>{$('#tg-status').textContent='傳送中…';try{await api('api/telegram/test',{});$('#tg-status').textContent='Telegram 已回覆成功；請看手機或頻道有沒有收到測試訊息。'}catch(e){$('#tg-status').textContent='沒有送出：'+e.message}};
function saveFile(name,contents,type){let url=URL.createObjectURL(new Blob(['\uFEFF'+contents],{type}));let a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('#cards').addEventListener('click',e=>{let b=e.target.closest('[data-run]');if(b)openResults([b.dataset.run])});
$('#cards').addEventListener('change',e=>{if(e.target.dataset.select){let id=e.target.dataset.select;e.target.checked?selected.add(id):selected.delete(id);cards()}});
$('#search').addEventListener('input',()=>{cards();if($('#results').open)refresh()});
$('#result-search').addEventListener('input',()=>refresh());
$('#grid').onclick=()=>{$('#cards').classList.remove('list');$('#grid').setAttribute('aria-pressed','true');$('#list').setAttribute('aria-pressed','false')};$('#list').onclick=()=>{$('#cards').classList.add('list');$('#list').setAttribute('aria-pressed','true');$('#grid').setAttribute('aria-pressed','false')};
$('#run-combined').onclick=()=>{if(!selected.size){$('#selection-count').textContent='請先勾選策略';return}openResults([...selected])};$('#clear-selection').onclick=()=>{selected.clear();cards()};$('#favorites').onclick=()=>openResults([],true);$('#close-results').onclick=()=>$('#results').close();
$('#settings-toggle').onclick=()=>{$('#settings').hidden=!$('#settings').hidden};$('#apply-settings').onclick=()=>{let before=result.length;refresh();$('#rule-note').textContent+=`　追加條件前 ${before}檔，修改後 ${result.length}檔。請記錄自己的假設。`};
function view(m){mode=m;$('#table-wrap').hidden=m!=='table';$('#charts').hidden=m!=='chart';$('#table-mode').setAttribute('aria-pressed',m==='table');$('#chart-mode').setAttribute('aria-pressed',m==='chart')};$('#table-mode').onclick=()=>view('table');$('#chart-mode').onclick=()=>view('chart');
$('#results').addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.sort){sortDown=sortKey===b.dataset.sort?!sortDown:false;sortKey=b.dataset.sort;refresh()}if(b.dataset.tab){tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(t=>{t.classList.toggle('active',t.dataset.tab===tab);t.setAttribute('aria-selected',t.dataset.tab===tab)});refresh()}if(b.dataset.fav){let s=b.dataset.fav;favorites.has(s)?favorites.delete(s):favorites.add(s);localStorage.setItem('picker-favorites',JSON.stringify([...favorites]));refresh();if(!$('#alert-panel').hidden)renderAlertRows()}if(b.dataset.detail)detail(b.dataset.detail);if(b.id==='detail-close')$('#detail').hidden=true});
$('#export-csv').onclick=()=>{let columns=[...base,...tabs[tab]],cell=v=>'"'+String(v??'').replaceAll('"','""')+'"';saveFile(`選股_${data.asof}.csv`,[columns.map(x=>cell(x[0])).join(','),...result.map(r=>columns.map(([,k])=>cell(r[k])).join(','))].join('\r\n'),'text/csv;charset=utf-8')};
for(let id of ['hypothesis','observation']){$('#'+id).value=localStorage.getItem('picker-'+id)||'';$('#'+id).addEventListener('input',()=>{localStorage.setItem('picker-'+id,$('#'+id).value);$('#note-status').textContent='已存於此瀏覽器；下載Markdown才是可帶走的檔案。'})}
$('#export-note').onclick=()=>{saveFile('我的選股實作紀錄.md',`# 我的選股實作紀錄\n\n資料來源：雪鴞\n資料日：${data.asof}\n範圍：${data.mode}／${data.universe_count}檔\n\n## 我的假設\n${$('#hypothesis').value||'待填'}\n\n## 修改與核對\n${$('#observation').value||'待填'}\n\n## 規格\n策略：${active.join('、')||[...selected].join('、')||'待填'}\n追加最低量：${$('#min-volume').value}張\n候選數：${result.length}\n\n## 下一步\n- 逐條核對來源、單位與資料日期\n- 補寫進場、失效、出場、部位與成本\n- 用 api.bt 驗證完整策略，保留負面結果\n- 失敗也存進知識庫，附證據與適用範圍\n`,'text/markdown;charset=utf-8');$('#note-status').textContent='已產生Markdown下載，請放進自己的Obsidian。'};
async function boot(){try{presets=await(await fetch('presets.json')).json();let response;if(location.hostname==='127.0.0.1'||location.hostname==='localhost')response=await fetch('local-data.json');if(!response?.ok)response=await fetch('demo-data.json');if(!response.ok)throw Error('資料檔未產生');data=await response.json();$('#data-status').textContent=`資料日 ${data.asof}｜${data.source}｜${data.mode==='teaching_sample'?`真實教學樣本${data.universe_count}檔，非全市場；本機版掃描${data.market_count}檔`:`本機股票範圍${data.universe_count}檔（含興櫃）` }。量為張。營收／財報須另核對公告時間。`;$('#tabs').innerHTML=Object.keys(tabs).map(t=>`<button role="tab" data-tab="${t}" aria-selected="${t===tab}" class="${t===tab?'active':''}">${t}</button>`).join('');cards()}catch(e){$('#data-status').textContent='資料載入失敗：'+e.message+'。請以本機HTTP服務開啟，或使用GitHub Pages。'}}boot();
